"""Initial migration - create all tables

Revision ID: 13969c357dee
Revises: 
Create Date: 2026-04-07 23:36:55.480885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13969c357dee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_point',
    sa.Column('knowledge_id', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False, comment='所属学科'),
    sa.Column('grade_level', sa.String(length=16), nullable=False, comment='适用年级'),
    sa.Column('knowledge_name', sa.String(length=128), nullable=False, comment='知识点名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='知识点描述'),
    sa.Column('parent_knowledge_id', sa.String(length=32), nullable=True, comment='父知识点ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_knowledge_id'], ['knowledge_point.knowledge_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('knowledge_id')
    )
    op.create_index('idx_knowledge_parent', 'knowledge_point', ['parent_knowledge_id'], unique=False)
    op.create_index('idx_knowledge_subject_grade', 'knowledge_point', ['subject', 'grade_level'], unique=False)
    op.create_table('student',
    sa.Column('student_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='学生姓名，敏感数据'),
    sa.Column('grade', sa.String(length=16), nullable=False, comment='年级'),
    sa.Column('preferred_subjects', sa.JSON(), nullable=True, comment='学科偏好列表'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_index('idx_student_grade', 'student', ['grade'], unique=False)
    op.create_index('idx_student_updated', 'student', ['updated_at'], unique=False)
    op.create_table('cognitive_gap',
    sa.Column('gap_id', sa.String(length=32), nullable=False),
    sa.Column('student_id', sa.String(length=32), nullable=False),
    sa.Column('gap_type', sa.String(length=32), nullable=False, comment='缺口类型'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态'),
    sa.Column('related_knowledge', sa.JSON(), nullable=False, comment='相关知识点'),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('crystallized_at', sa.DateTime(), nullable=True, comment='固化时间'),
    sa.Column('occurrence_count', sa.Integer(), nullable=False, comment='出现次数'),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'crystallized', 'dismissed')", name='ck_gap_status'),
    sa.CheckConstraint('occurrence_count >= 1', name='ck_gap_occurrence'),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gap_id')
    )
    op.create_index('idx_gap_crystallized', 'cognitive_gap', ['crystallized_at'], unique=False)
    op.create_index('idx_gap_status', 'cognitive_gap', ['status', 'discovered_at'], unique=False)
    op.create_index('idx_gap_student', 'cognitive_gap', ['student_id', 'status', 'discovered_at'], unique=False)
    op.create_table('cognitive_profile',
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('student_id', sa.String(length=32), nullable=False),
    sa.Column('thinking_style', sa.JSON(), nullable=True, comment='思维风格特征'),
    sa.Column('error_dna', sa.JSON(), nullable=True, comment='错误DNA模式'),
    sa.Column('zpd_boundary', sa.JSON(), nullable=True, comment='最近发展区边界'),
    sa.Column('cognitive_features', sa.JSON(), nullable=True, comment='认知特征向量'),
    sa.Column('crystallized_at', sa.DateTime(), nullable=True, comment='固化时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index('idx_profile_crystallized', 'cognitive_profile', ['crystallized_at'], unique=False)
    op.create_index('idx_profile_student', 'cognitive_profile', ['student_id'], unique=False)
    op.create_table('homework',
    sa.Column('homework_id', sa.String(length=32), nullable=False),
    sa.Column('student_id', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False, comment='学科'),
    sa.Column('page_count', sa.Integer(), nullable=False, comment='页数'),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False, comment='上传时间'),
    sa.Column('image_urls', sa.JSON(), nullable=False, comment='原图URL列表'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态: active/archived/deleted'),
    sa.Column('archived_at', sa.DateTime(), nullable=True, comment='归档时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'archived', 'deleted')", name='ck_homework_status'),
    sa.CheckConstraint('page_count > 0', name='ck_homework_page_count'),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('homework_id')
    )
    op.create_index('idx_homework_status', 'homework', ['status', 'archived_at'], unique=False)
    op.create_index('idx_homework_student', 'homework', ['student_id', 'uploaded_at'], unique=False)
    op.create_index('idx_homework_uploaded', 'homework', ['uploaded_at'], unique=False)
    op.create_table('knowledge_dependency',
    sa.Column('dependency_id', sa.String(length=32), nullable=False),
    sa.Column('knowledge_id', sa.String(length=32), nullable=False),
    sa.Column('prerequisite_id', sa.String(length=32), nullable=False),
    sa.Column('dependency_strength', sa.Float(), nullable=False, comment='依赖强度'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('dependency_strength >= 0 AND dependency_strength <= 1', name='ck_dependency_strength'),
    sa.CheckConstraint('knowledge_id != prerequisite_id', name='ck_dependency_no_self_ref'),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_point.knowledge_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['knowledge_point.knowledge_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dependency_id'),
    sa.UniqueConstraint('knowledge_id', 'prerequisite_id', name='uq_dependency')
    )
    op.create_index('idx_dependency_knowledge', 'knowledge_dependency', ['knowledge_id'], unique=False)
    op.create_index('idx_dependency_prereq', 'knowledge_dependency', ['prerequisite_id'], unique=False)
    op.create_table('misconception',
    sa.Column('misconception_id', sa.String(length=32), nullable=False),
    sa.Column('knowledge_id', sa.String(length=32), nullable=False),
    sa.Column('misconception_pattern', sa.Text(), nullable=False, comment='误解模式描述'),
    sa.Column('correct_concept', sa.Text(), nullable=False, comment='正确概念描述'),
    sa.Column('verified_count', sa.Integer(), nullable=False, comment='验证次数'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('verified_count >= 0', name='ck_misconception_verified'),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_point.knowledge_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('misconception_id')
    )
    op.create_index('idx_misconception_knowledge', 'misconception', ['knowledge_id'], unique=False)
    op.create_table('parent_description',
    sa.Column('description_id', sa.String(length=32), nullable=False),
    sa.Column('student_id', sa.String(length=32), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False, comment='原始描述文本，敏感数据'),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False, comment='来源类型'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("source_type IN ('text', 'voice', 'video')", name='ck_description_source'),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('description_id')
    )
    op.create_index('idx_description_student', 'parent_description', ['student_id', 'submitted_at'], unique=False)
    op.create_table('student_knowledge_mastery',
    sa.Column('mastery_id', sa.String(length=32), nullable=False),
    sa.Column('student_id', sa.String(length=32), nullable=False),
    sa.Column('knowledge_id', sa.String(length=32), nullable=False),
    sa.Column('mastery_level', sa.Float(), nullable=False, comment='掌握度(0-1)'),
    sa.Column('practice_count', sa.Integer(), nullable=False, comment='练习次数'),
    sa.Column('last_practiced', sa.DateTime(), nullable=True, comment='最后练习时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('mastery_level >= 0 AND mastery_level <= 1', name='ck_mastery_level'),
    sa.CheckConstraint('practice_count >= 0', name='ck_mastery_practice_count'),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_point.knowledge_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mastery_id'),
    sa.UniqueConstraint('student_id', 'knowledge_id', name='uq_student_knowledge')
    )
    op.create_index('idx_mastery_level', 'student_knowledge_mastery', ['mastery_level', 'practice_count'], unique=False)
    op.create_index('idx_mastery_student', 'student_knowledge_mastery', ['student_id', 'mastery_level'], unique=False)
    op.create_table('description_parse',
    sa.Column('parse_id', sa.String(length=32), nullable=False),
    sa.Column('description_id', sa.String(length=32), nullable=False),
    sa.Column('explicit_statements', sa.JSON(), nullable=False, comment='显性声明'),
    sa.Column('implicit_observations', sa.JSON(), nullable=False, comment='隐性观察'),
    sa.Column('confidence_score', sa.Float(), nullable=False, comment='解析置信度'),
    sa.Column('parsed_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 1', name='ck_parse_confidence'),
    sa.ForeignKeyConstraint(['description_id'], ['parent_description.description_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parse_id'),
    sa.UniqueConstraint('description_id')
    )
    op.create_index('idx_parse_confidence', 'description_parse', ['confidence_score'], unique=False)
    op.create_index('idx_parse_description', 'description_parse', ['description_id'], unique=False)
    op.create_table('homework_analysis',
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('homework_id', sa.String(length=32), nullable=False),
    sa.Column('cognitive_features', sa.JSON(), nullable=True, comment='提取的认知特征'),
    sa.Column('key_decisions', sa.JSON(), nullable=True, comment='关键决策节点'),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homework.homework_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id'),
    sa.UniqueConstraint('homework_id')
    )
    op.create_index('idx_analysis_homework', 'homework_analysis', ['homework_id'], unique=False)
    op.create_table('question',
    sa.Column('question_id', sa.String(length=32), nullable=False),
    sa.Column('homework_id', sa.String(length=32), nullable=False),
    sa.Column('original_image_url', sa.String(length=512), nullable=True, comment='原题图片URL'),
    sa.Column('ocr_text', sa.Text(), nullable=True, comment='OCR识别文本'),
    sa.Column('parsed_content', sa.JSON(), nullable=True, comment='结构化解析内容'),
    sa.Column('question_number', sa.Integer(), nullable=False, comment='题号'),
    sa.Column('difficulty_level', sa.String(length=16), nullable=True, comment='难度等级'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['homework_id'], ['homework.homework_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index('idx_question_homework', 'question', ['homework_id', 'question_number'], unique=False)
    op.create_table('question_knowledge_tag',
    sa.Column('tag_id', sa.String(length=32), nullable=False),
    sa.Column('question_id', sa.String(length=32), nullable=False),
    sa.Column('knowledge_id', sa.String(length=32), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False, comment='相关度分数'),
    sa.CheckConstraint('relevance_score >= 0 AND relevance_score <= 1', name='ck_tag_relevance'),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_point.knowledge_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('question_id', 'knowledge_id', name='uq_question_knowledge_tag')
    )
    op.create_index('idx_tag_knowledge', 'question_knowledge_tag', ['knowledge_id'], unique=False)
    op.create_table('student_answer',
    sa.Column('answer_id', sa.String(length=32), nullable=False),
    sa.Column('question_id', sa.String(length=32), nullable=False),
    sa.Column('student_id', sa.String(length=32), nullable=False),
    sa.Column('answer_content', sa.Text(), nullable=False, comment='答案内容'),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True, comment='是否正确'),
    sa.Column('confidence_score', sa.Float(), nullable=True, comment='置信度'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name='ck_answer_confidence'),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_index('idx_answer_correct', 'student_answer', ['student_id', 'is_correct', 'answered_at'], unique=False)
    op.create_index('idx_answer_question', 'student_answer', ['question_id'], unique=False)
    op.create_index('idx_answer_student', 'student_answer', ['student_id', 'answered_at'], unique=False)
    op.create_table('variant_question',
    sa.Column('variant_id', sa.String(length=32), nullable=False),
    sa.Column('original_question_id', sa.String(length=32), nullable=False),
    sa.Column('variant_type', sa.String(length=32), nullable=False, comment='变形类型'),
    sa.Column('variant_content', sa.Text(), nullable=False, comment='变形题内容'),
    sa.Column('validation_status', sa.String(length=16), nullable=False, comment='验证状态'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("validation_status IN ('pending', 'validated', 'failed', 'expired')", name='ck_validation_status'),
    sa.CheckConstraint("variant_type IN ('numeric_change', 'inverse_operation', 'context_transfer', 'difficulty_adjust', 'format_change')", name='ck_variant_type'),
    sa.ForeignKeyConstraint(['original_question_id'], ['question.question_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variant_id')
    )
    op.create_index('idx_variant_original', 'variant_question', ['original_question_id'], unique=False)
    op.create_index('idx_variant_status', 'variant_question', ['validation_status', 'created_at'], unique=False)
    op.create_table('answer_trace',
    sa.Column('trace_id', sa.String(length=32), nullable=False),
    sa.Column('answer_id', sa.String(length=32), nullable=False),
    sa.Column('decision_path', sa.JSON(), nullable=False, comment='决策路径详情'),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['student_answer.answer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trace_id')
    )
    op.create_index('idx_trace_answer', 'answer_trace', ['answer_id'], unique=False)
    op.create_table('error_diagnosis',
    sa.Column('diagnosis_id', sa.String(length=32), nullable=False),
    sa.Column('answer_id', sa.String(length=32), nullable=False),
    sa.Column('question_id', sa.String(length=32), nullable=False),
    sa.Column('student_id', sa.String(length=32), nullable=False),
    sa.Column('error_type', sa.String(length=32), nullable=False, comment='错因类型'),
    sa.Column('knowledge_tags', sa.JSON(), nullable=False, comment='考点标签'),
    sa.Column('confidence_score', sa.Float(), nullable=False, comment='诊断置信度'),
    sa.Column('diagnosis_path', sa.Text(), nullable=True, comment='诊断选项路径摘要'),
    sa.Column('diagnosed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("error_type IN ('careless', 'method_error', 'concept_gap', 'calculation_error', 'reading_error', 'unknown')", name='ck_diagnosis_error_type'),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 1', name='ck_diagnosis_confidence'),
    sa.ForeignKeyConstraint(['answer_id'], ['student_answer.answer_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('diagnosis_id')
    )
    op.create_index('idx_diagnosis_confidence', 'error_diagnosis', ['confidence_score'], unique=False)
    op.create_index('idx_diagnosis_error_type', 'error_diagnosis', ['student_id', 'error_type', 'diagnosed_at'], unique=False)
    op.create_index('idx_diagnosis_student', 'error_diagnosis', ['student_id', 'diagnosed_at'], unique=False)
    op.create_table('variant_answer',
    sa.Column('variant_answer_id', sa.String(length=32), nullable=False),
    sa.Column('variant_id', sa.String(length=32), nullable=False),
    sa.Column('student_id', sa.String(length=32), nullable=False),
    sa.Column('answer_content', sa.Text(), nullable=False, comment='答案内容'),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['variant_question.variant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('variant_answer_id')
    )
    op.create_index('idx_variant_answer_result', 'variant_answer', ['variant_id', 'is_correct'], unique=False)
    op.create_index('idx_variant_answer_student', 'variant_answer', ['student_id', 'variant_id'], unique=False)
    op.create_table('diagnosis_path',
    sa.Column('path_id', sa.String(length=32), nullable=False),
    sa.Column('diagnosis_id', sa.String(length=32), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False, comment='步骤序号'),
    sa.Column('option_selected', sa.String(length=64), nullable=False, comment='选择的选项'),
    sa.Column('reasoning', sa.Text(), nullable=True, comment='选择理由'),
    sa.CheckConstraint('step_number > 0', name='ck_path_step_number'),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['error_diagnosis.diagnosis_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('path_id')
    )
    op.create_index('idx_path_diagnosis', 'diagnosis_path', ['diagnosis_id', 'step_number'], unique=False)
    op.create_table('gap_evidence',
    sa.Column('evidence_id', sa.String(length=32), nullable=False),
    sa.Column('gap_id', sa.String(length=32), nullable=False),
    sa.Column('diagnosis_id', sa.String(length=32), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False, comment='证据类型'),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("evidence_type IN ('initial_diagnosis', 'repeat_error', 'variant_failed', 'cross_homework')", name='ck_evidence_type'),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['error_diagnosis.diagnosis_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gap_id'], ['cognitive_gap.gap_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index('idx_evidence_diagnosis', 'gap_evidence', ['diagnosis_id'], unique=False)
    op.create_index('idx_evidence_gap', 'gap_evidence', ['gap_id', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_evidence_gap', table_name='gap_evidence')
    op.drop_index('idx_evidence_diagnosis', table_name='gap_evidence')
    op.drop_table('gap_evidence')
    op.drop_index('idx_path_diagnosis', table_name='diagnosis_path')
    op.drop_table('diagnosis_path')
    op.drop_index('idx_variant_answer_student', table_name='variant_answer')
    op.drop_index('idx_variant_answer_result', table_name='variant_answer')
    op.drop_table('variant_answer')
    op.drop_index('idx_diagnosis_student', table_name='error_diagnosis')
    op.drop_index('idx_diagnosis_error_type', table_name='error_diagnosis')
    op.drop_index('idx_diagnosis_confidence', table_name='error_diagnosis')
    op.drop_table('error_diagnosis')
    op.drop_index('idx_trace_answer', table_name='answer_trace')
    op.drop_table('answer_trace')
    op.drop_index('idx_variant_status', table_name='variant_question')
    op.drop_index('idx_variant_original', table_name='variant_question')
    op.drop_table('variant_question')
    op.drop_index('idx_answer_student', table_name='student_answer')
    op.drop_index('idx_answer_question', table_name='student_answer')
    op.drop_index('idx_answer_correct', table_name='student_answer')
    op.drop_table('student_answer')
    op.drop_index('idx_tag_knowledge', table_name='question_knowledge_tag')
    op.drop_table('question_knowledge_tag')
    op.drop_index('idx_question_homework', table_name='question')
    op.drop_table('question')
    op.drop_index('idx_analysis_homework', table_name='homework_analysis')
    op.drop_table('homework_analysis')
    op.drop_index('idx_parse_description', table_name='description_parse')
    op.drop_index('idx_parse_confidence', table_name='description_parse')
    op.drop_table('description_parse')
    op.drop_index('idx_mastery_student', table_name='student_knowledge_mastery')
    op.drop_index('idx_mastery_level', table_name='student_knowledge_mastery')
    op.drop_table('student_knowledge_mastery')
    op.drop_index('idx_description_student', table_name='parent_description')
    op.drop_table('parent_description')
    op.drop_index('idx_misconception_knowledge', table_name='misconception')
    op.drop_table('misconception')
    op.drop_index('idx_dependency_prereq', table_name='knowledge_dependency')
    op.drop_index('idx_dependency_knowledge', table_name='knowledge_dependency')
    op.drop_table('knowledge_dependency')
    op.drop_index('idx_homework_uploaded', table_name='homework')
    op.drop_index('idx_homework_student', table_name='homework')
    op.drop_index('idx_homework_status', table_name='homework')
    op.drop_table('homework')
    op.drop_index('idx_profile_student', table_name='cognitive_profile')
    op.drop_index('idx_profile_crystallized', table_name='cognitive_profile')
    op.drop_table('cognitive_profile')
    op.drop_index('idx_gap_student', table_name='cognitive_gap')
    op.drop_index('idx_gap_status', table_name='cognitive_gap')
    op.drop_index('idx_gap_crystallized', table_name='cognitive_gap')
    op.drop_table('cognitive_gap')
    op.drop_index('idx_student_updated', table_name='student')
    op.drop_index('idx_student_grade', table_name='student')
    op.drop_table('student')
    op.drop_index('idx_knowledge_subject_grade', table_name='knowledge_point')
    op.drop_index('idx_knowledge_parent', table_name='knowledge_point')
    op.drop_table('knowledge_point')
    # ### end Alembic commands ###
